"""add flags for todos

Revision ID: 468200e69c78
Revises: 49b2c0d9074e
Create Date: 2025-07-15 19:49:01.054820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '468200e69c78'
down_revision: Union[str, Sequence[str], None] = '49b2c0d9074e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('is_completed', sa.Boolean(), server_default='f', nullable=False))
    op.add_column('todos', sa.Column('is_deleted', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'is_deleted')
    op.drop_column('todos', 'is_completed')
    # ### end Alembic commands ###
